# Pacloud project
# Create a custom resource with CloudFormation: SpotFleet
# https://github.com/OlivierBP/Pacloud
# Created 2018-03-29 by BAL-PETRE Olivier
# License MIT

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Create a custom resource. Create a SpotFleet


Resources:

  SpotFleet:
    Type: 'Custom::SpotFleet'
    Version: "1.0"
    Properties:
      ServiceToken: arn:aws:lambda:eu-west-1:912175495967:function:LambdaCustomResourceSpotFleet

      AllocationStrategy: !ImportValue AllocationStrategy
      ExcessCapacityTerminationPolicy: default
      IamFleetRole: !ImportValue IamFleetRole
      ReplaceUnhealthyInstances: true
      TargetCapacity: !ImportValue TargetCapacity
      TerminateInstancesWithExpiration: true
      Type: maintain

      LaunchSpecifications:
      - EbsOptimized: false
        EbsSize: 30
        InstanceInterruptionBehavior: hibernate
        IamInstanceProfile:
          Arn: !ImportValue IamInstanceProfile
        ImageId: !ImportValue ImageId
        InstanceType: !ImportValue InstanceType
        KeyName: !ImportValue KeyName
        Monitoring:
          Enabled: true
        SecurityGroups:
        - GroupId: !ImportValue SecurityGroups
        SubnetId: !ImportValue SubnetId
        TagSpecifications:
        - ResourceType: instance
          Tags:
          - Key: Project
            Value: Pacloud
          - Key: Name
            Value: PacloudSpotInstance
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            # Fail on error
            set -e
            # To update to the latest version
            docker pull olivierbp/pacloud



Outputs:
  SpotFleetRequestId:
    Value: !GetAtt SpotFleet.SpotFleetRequestId
    Description: Return the ID of the spotfleet created. NEEDED TO CAN DELETE/UPADTE the stack, don't delete and don't rename

  TargetCapacity:
    Value: !ImportValue TargetCapacity
    Description: Target capacity of the spotfleet

