# Pacloud project
# Create a custom resource with CloudFormation: SpotFleet
# https://github.com/OlivierBP/Pacloud
# Created 2018-03-29 by BAL-PETRE Olivier
# License MIT 

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Create a custom resource. Create a SpotFleet


Resources:   

  SpotFleet:
    Type: 'Custom::SpotFleet'
    Version: "1.0"
    Properties:
      ServiceToken: arn:aws:lambda:eu-west-1:912175495967:function:LambdaCustomResourceSpotFleet
      
      AllocationStrategy: !ImportValue AllocationStrategy
      ExcessCapacityTerminationPolicy: default
      IamFleetRole: !ImportValue IamFleetRole
      ReplaceUnhealthyInstances: true
      TargetCapacity: !ImportValue TargetCapacity
      TerminateInstancesWithExpiration: true
      Type: maintain
      
      LaunchSpecifications:
      - EbsOptimized: false
        InstanceInterruptionBehavior: hibernate
        IamInstanceProfile: 
          Arn: !ImportValue IamInstanceProfile
        ImageId: !ImportValue ImageId
        InstanceType: !ImportValue InstanceType
        KeyName: !ImportValue KeyName
        Monitoring: 
          Enabled: true
        SecurityGroups:
        - GroupId: !ImportValue SecurityGroups
        SubnetId: !ImportValue SubnetId
        TagSpecifications: 
        - ResourceType: instance
          Tags:
          - Key: Project
            Value: Pacloud
          - Key: Name
            Value: PacloudSpotInstance_cfd



