# Pacloud project
# Network
# https://github.com/OlivierBP/Pacloud
# Created 2018-03-18 by BAL-PETRE Olivier
# License MIT

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creation of the network (NAT included)



Resources:
  # VPC
  VpcPacloudSpotFleet:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: PacloudSpotFleet

  # Internet Gateway for the VPC
  IgVpcPacloudSpotFleet:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: IgVpcPacloudSpotFleet
    DependsOn:
      - VpcPacloudSpotFleet

  # Need to attach the Internet Gateway to the VPC
  VPCGatewayAttachmentForIg:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref IgVpcPacloudSpotFleet
      VpcId: !Ref VpcPacloudSpotFleet

  # Private subnets for all the EC2 spot instances
  PrivateSubnetPacloudSpotFleet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VpcPacloudSpotFleet
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: eu-west-1a
      Tags:
        - Key: Name
          Value: PrivateSubnetPacloudSpotFleet1
    DependsOn:
      - VpcPacloudSpotFleet
  PrivateSubnetPacloudSpotFleet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VpcPacloudSpotFleet
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: eu-west-1b
      Tags:
        - Key: Name
          Value: PrivateSubnetPacloudSpotFleet2
    DependsOn:
      - VpcPacloudSpotFleet
  PrivateSubnetPacloudSpotFleet3:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VpcPacloudSpotFleet
      CidrBlock: 10.0.5.0/24
      AvailabilityZone: eu-west-1c
      Tags:
        - Key: Name
          Value: PrivateSubnetPacloudSpotFleet3
    DependsOn:
      - VpcPacloudSpotFleet

  # Public subnet for the bastion server and the NAT
  PublicSubnetPacloud1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VpcPacloudSpotFleet
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: eu-west-1a
      Tags:
        - Key: Name
          Value: PublicSubnetPacloud1
    DependsOn:
      - VpcPacloudSpotFleet
  # Create the default route to internet for the public subnet 1
  RouteTablePublicSubnet1:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VpcPacloudSpotFleet
      Tags:
        - Key: Name
          Value: RouteTablePublicSubnet1
  RouteToIgPublicSubnet1:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref RouteTablePublicSubnet1
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IgVpcPacloudSpotFleet
    DependsOn: VPCGatewayAttachmentForIg
  SubnetRouteTableAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref RouteTablePublicSubnet1
      SubnetId: !Ref PublicSubnetPacloud1

  # Public subnet for the bastion server and the NAT
  PublicSubnetPacloud2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VpcPacloudSpotFleet
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: eu-west-1b
      Tags:
        - Key: Name
          Value: PublicSubnetPacloud2
    DependsOn:
      - VpcPacloudSpotFleet
  # Create the default route to internet for the public subnet 2
  RouteTablePublicSubnet2:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VpcPacloudSpotFleet
      Tags:
        - Key: Name
          Value: RouteTablePublicSubnet2
  RouteToIgPublicSubnet2:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref RouteTablePublicSubnet2
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IgVpcPacloudSpotFleet
    DependsOn: VPCGatewayAttachmentForIg
  SubnetRouteTableAssociation2:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref RouteTablePublicSubnet2
      SubnetId: !Ref PublicSubnetPacloud2

  # Public subnet for the bastion server and the NAT
  PublicSubnetPacloud3:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VpcPacloudSpotFleet
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: eu-west-1c
      Tags:
        - Key: Name
          Value: PublicSubnetPacloud3
    DependsOn:
      - VpcPacloudSpotFleet
  # Create the default route to internet for the public subnet 3
  RouteTablePublicSubnet3:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VpcPacloudSpotFleet
      Tags:
        - Key: Name
          Value: RouteTablePublicSubnet3
  RouteToIgPublicSubnet3:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref RouteTablePublicSubnet3
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IgVpcPacloudSpotFleet
    DependsOn: VPCGatewayAttachmentForIg
  SubnetRouteTableAssociation3:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref RouteTablePublicSubnet3
      SubnetId: !Ref PublicSubnetPacloud3



Outputs:
  VpcPacloudSpotFleet:
    Value: !Ref VpcPacloudSpotFleet
  PublicSubnetPacloud1:
    Value: !Ref PublicSubnetPacloud1
  PublicSubnetPacloud2:
    Value: !Ref PublicSubnetPacloud2
  PublicSubnetPacloud3:
    Value: !Ref PublicSubnetPacloud3
  PrivateSubnetPacloudSpotFleet1:
    Value: !Ref PrivateSubnetPacloudSpotFleet1
  PrivateSubnetPacloudSpotFleet2:
    Value: !Ref PrivateSubnetPacloudSpotFleet2
  PrivateSubnetPacloudSpotFleet3:
    Value: !Ref PrivateSubnetPacloudSpotFleet3
